### DISCUSSION TITLE
CAP_NET_RAW capability has no effect

### DISCUSSION THREAD

**Discussion by panpur** [crc-org/crc#2939] [Q&A]
Hello,

I'm getting error ```Bad file descriptor``` when creating raw socket in c++ aplication in CRC 1.37 (Centos 8).
Here's snippet of uid1000 SCC:
```
allowedCapabilities:
- CAP_NET_RAW
requiredDropCapabilities:
- KILL
- SETUID
- SETGID
runAsUser:
  type: MustRunAs
  uid: 1000
```
I've set the SCC to service acc using ```oc adm policy add-scc-to-user uid1000 -z runasuid1000 --as system:admin```
Then in deployment config:
```
serviceAccount: runasuid1000
serviceAccountName: runasuid1000
containers:
  securityContext:
  - capabilities:
      add:
      - CAP_NET_RAW
```
Am I missing something?
