### ISSUE TITLE
[BUG] Trying to run amd64 images on M1 arm fails

### ISSUE THREAD

**Issue by IBMRob** [crc-org/crc#3483]
### General information

  * OS: macOS 
  * Hypervisor: default
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop 

## CRC version
```bash
convery@Robs-M1 ibm-appconnect % crc version
CRC version: 2.12.0+ea98bb41
OpenShift version: 4.11.18
Podman version: 4.2.0
```
  
## CRC status
```bash
DEBU CRC version: 2.12.0+ea98bb41                 
DEBU OpenShift version: 4.11.18                   
DEBU Podman version: 4.2.0                        
DEBU Running 'crc status'                         
CRC VM:          Running
OpenShift:       Running (v4.11.18)
RAM Usage:       8.041GB of 9.353GB
Disk Usage:      15.14GB of 32.74GB (Inside the CRC VM)
Cache Usage:     73.63GB
Cache Directory: /Users/convery/.crc/cache
```

## CRC config
```bash
- consent-telemetry                     : no
```

## Host Operating System
```bash
ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C65
```

### Steps to reproduce

  1. Add a catalog source which doesn't have an ARM version but does have an amd64 version i.e. 
 ```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM Operator Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-operator-catalog
  updateStrategy:
    registryPoll:
      interval: 45m
```
  3. 
  4. 
  5. 

### Expected

I was hoping that it would be possible to get OCP to fall back and use the amd64 images like its possible on docker i.e. I can pull the image using `docker pull -platform=linux/amd64  icr.io/cpopen/ibm-operator-catalog` and then run it as a normal image using `docker run icr.io/cpopen/ibm-operator-catalog`

Is it possible to get it to run amd64 containers? 

### Actual

Pull fails due to `Failed to pull image "icr.io/cpopen/ibm-operator-catalog": rpc error: code = Unknown desc = choosing image instance: no image found in manifest list for architecture arm64, variant "v8", OS linux`

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.
