### ISSUE TITLE
[BUG] Unable to create files in mounted volumes

### ISSUE THREAD

**Issue by bobbygryzynger** [crc-org/crc#3589]
### General information

  * OS: Linux
  * Hypervisor: KVM 
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop

## CRC version
```bash
$ crc version
CRC version: 2.12.0+74565a6
OpenShift version: 4.11.18
Podman version: 4.2.0
```
  
## CRC status
```bash
$ crc status --log-level debug
DEBU CRC version: 2.12.0+74565a6                  
DEBU OpenShift version: 4.11.18                   
DEBU Podman version: 4.2.0                        
DEBU Running 'crc status'                         
CRC VM:          Running
OpenShift:       Running (v4.11.18)
RAM Usage:       11.22GB of 14.68GB
Disk Usage:      20.82GB of 32.74GB (Inside the CRC VM)
Cache Usage:     112.5GB
Cache Directory: /home/bgryzyng/.crc/cache
```

## CRC config
```bash
$ crc config view
- consent-telemetry                     : yes
- cpus                                  : 6
- enable-cluster-monitoring             : true
- host-network-access                   : true
- memory                                : 14336
- network-mode                          : user
```

## Host Operating System
```bash
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="36 (Workstation Edition)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
SUPPORT_END=2023-05-16
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### Steps to reproduce

  1.  Create a Deployment object with a mounted volume
  2. Log into the running pod
  3.  Attempt to create a file in the mounted path with `touch /path/to/volume/test.txt`

### Expected
File creation should succeed.

### Actual
File creation fails with ` Permission denied` error. 

`crc delete` and re-running `crc setup` did not resolve the issue.

Adding (similar to #3440) did not resolve the issue.
```yaml
securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
```

**Comment by gbraad** [comment]
Does the machine have SELinux enabled?

> File creation fails with ` Permission denied` error.

Can you include steps to explain 'when'/'who'/'where' the creation fails.

> Log into the running pod

Such as, what kind of application is running. What is the image based on.

**Comment by anjannath** [comment]
@bobbygryzynger It'll be helpful to debug if you share the deployment and pvc yaml that you used

I tried with the following pvc and deployment and was able to create a file in the mounted dir

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testpvc-claim
  namespace: testpvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
```
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-dep
  name: my-dep
  namespace: testpvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dep
  template:
    metadata:
      labels:
        app: my-dep
    spec:
      volumes:
        - name: testvol
          persistentVolumeClaim:
            claimName: testpvc-claim
      containers:
      - image: busybox
        name: busybox-pod
        command: ["/bin/sh", "-c"]
        args: [ "tail -f /dev/null" ]
        volumeMounts:
          - mountPath: /mnt/testpvc
            name: testvol
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
```

Once the pod is created, tried to create a file in `/mnt/testpvc`:
```
❯ oc get pods
NAME                      READY   STATUS    RESTARTS   AGE
my-dep-5987f97f6b-h5tmn   1/1     Running   0          30s

❯ oc exec -it pod/my-dep-5987f97f6b-h5tmn /bin/sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.

~ $ ls
bin    dev    etc    home   lib    lib64  mnt    proc   root   run    sys    tmp    usr    var
~ $ ls /mnt/testpvc/

~ $ ls -al /mnt/testpvc/
total 0
drwxrwsr-x    2 root     10006600         6 Apr 11 08:28 .
drwxr-xr-x    3 root     root            21 Apr 11 08:28 ..

~ $ touch /mnt/testpvc/test

~ $ ls -al /mnt/testpvc/
total 4
drwxrwsr-x    2 root     10006600        19 Apr 11 08:30 .
drwxr-xr-x    3 root     root            21 Apr 11 08:28 ..
-rw-rw-rw-    1 10006600 10006600        19 Apr 11 08:30 test
```

**Comment by bobbygryzynger** [comment]
It looks like the issue I was having was ultimately because I was using the `default` namespace. If I create my objects in a different namespace, then I am able to access the mounted volumes as expected.

**Comment by anjannath** [comment]
With this i was able to get the desired permissions on the `default` namespace as well, note the SecurityContexts.. for the deployment i added `fsGroup: 9999` and for the containers in it `runAsUser: 9999` and `runAsGroup: 9999`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-dep
  name: my-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dep
  template:
    metadata:
      labels:
        app: my-dep
    spec:
      volumes:
        - name: testvol
          persistentVolumeClaim:
            claimName: testpvc-claim
      containers:
      - image: busybox
        name: busybox-pod
        command: ["/bin/sh", "-c"]
        args: [ "tail -f /dev/null" ]
        volumeMounts:
          - mountPath: /mnt/testpvc
            name: testvol
        securityContext:
          runAsUser: 9999
          runAsGroup: 9999
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      securityContext:
        fsGroup: 9999
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop: ["ALL"]
```
