### ISSUE TITLE
kubeconfig: Add `/cluster` suffix to the `user` `AuthInfos` entries

### ISSUE THREAD

**Issue by cfergeau** [crc-org/crc#3940]
Looking at `.kube/config`, I noticed that entries for other clusters look like:
```
contexts:
- context:
    cluster: api-ci-xxx:6443
    namespace: origin
    user: cfergeau/api-ci-xxx:6443
  name: origin/api-ci-xxx:6443/cfergeau
users:
- name: cfergeau/api-ci-xxx:6443
  user:
    token: sha256~yyy
```

By contrast, the entries added by crc are:
```
contexts:
- context:
    cluster: api-crc-testing:6443
    namespace: default
    user: kubeadmin
  name: crc-admin
- context:
    cluster: api-crc-testing:6443
    namespace: default
    user: developer
  name: crc-developer
users:
- name: developer
  user:
    token: sha256~yyy
- name: kubeadmin
  user:
    token: sha256~zzz
```

Changing the user names to `developer/api-crc-testing:6443` and `kubeadmin/api-crc-testing:6443` would make them less ambiguous.

**Comment by praveenkumar** [comment]
I think it is just the tooling side when you use `oc login` it does add `/cluster` suffix as part of name but if you create plain k8s cluster (like using kind/minikube/rancher) it doesn't have that suffix. So if a user using multiple cluster it is not ambiguous.

```
$ oc config get-contexts -o name
default/api-j9uzu-y6fxu-668-ki63-p3-openshiftapps-com:443/cluster-admin
default/api-mofrw-ucwdu-x9d-arwe-p3-openshiftapps-com:443/cluster-admin
dev-sandbox-context
kind-kind
kind-kind-cluster
microshift
openshift-dns/api-dzcvb-gyo7k-boc-t9mj-p3-openshiftapps-com:443/cluster-admin
prkumar-dev/api-sandbox-m2-ll9k-p1-openshiftapps-com:6443/prkumar
rancher-desktop
```

**Comment by cfergeau** [comment]
I'm not talking about the context names, which have a `crc-` prefix in our case, but about the `AUTHINFO` column in `oc config get-contexts` output. I don't know how these are named in other clusters, but looking at `~/.kube/config` I don't see how this can work without collisions if there is no namespacing at all.

**Comment by anjannath** [comment]
tried adding duplicate entries by hand in the `users` list and when it has duplicate entries, `oc` errors out with the following error:
```
error: error loading config file "/Users/anath/.kube/config": error converting *[]NamedAuthInfo into *map[string]*api.AuthInfo: duplicate name "user" in list:
```

looking at the code on crc for updating the kubeconfig file, i.e `mergConfig`for microshift and `writeKubeConfig` for ocp it'd be simpler to update the kubeconfig file on `snc` during the createdisk phase than making changes to the file during `crc start`

**Comment by cfergeau** [comment]
> tried adding duplicate entries by hand in the `users` list and when it has duplicate entries, `oc` errors out with the following error:
> 
> ```
> error: error loading config file "/Users/anath/.kube/config": error converting *[]NamedAuthInfo into *map[string]*api.AuthInfo: duplicate name "user" in list:
> ```
> 
> looking at the code on crc for updating the kubeconfig file, i.e `mergConfig`for microshift and `writeKubeConfig` for ocp it'd be simpler to update the kubeconfig file on `snc` during the createdisk phase than making changes to the file during `crc start`

Ah sure if it's simpler to improve this in `snc`, this works too!

**Comment by anjannath** [comment]
looking at this again, it seems only the ocp bundle has a kubeconfig file, while the microshift preset the bundle has an empty kubeconfig, the kubeconfig file is copied from the VM by crc after `crc start`, so we have to modify it from crc itself, i've opened #4020 for this

**Comment by cfergeau** [comment]
>  while the microshift preset [...] the kubeconfig file is copied from the VM by crc

And the kubeconfig file created in the VM does not have suffixes?

**Comment by praveenkumar** [comment]
I am not sure why we are pushing it because context is how oc/kubectl or any component which communicate to the cluster and according to doc https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/#Context it is tuple of cluster endpoint, user and namespace so having the collision is rare until user manually edit the kubeconfig file and put same user entry for the cluster, or I am missing something here. It has been more than 1 year since we are added this and didn't receive any issue around the collision.

**Comment by cfergeau** [comment]
This is not about the `context` section, this is about the `users` section, which is outside of `contexts`
See also https://github.com/crc-org/crc/issues/3940#issuecomment-1845104910

**Comment by praveenkumar** [comment]
Yes I am referring to user section which is consumed by context not directly consumed by client. Also if we really want to have it in sync than I only want to update the user which we add not the whole kubeconfig file which is updated by different tools which is what #4020 is doing.

- https://github.com/crc-org/crc/compare/main...praveenkumar:crc:issue_3920

**Comment by cfergeau** [comment]
> Yes I am referring to user section which is consumed by context not directly consumed by client.

With non-suffixed/namespaced usernames (and this is what crc is doing at the moment), this breaks easily, my 2 clusters will try to use the same token:

```
contexts:
- context:
    cluster: api-crc-testing:6443
    namespace: default
    user: kubeadmin
  name: crc-admin
- context:
    cluster: api-example-com:6443
    namespace: default
    user: kubeadmin
  name: example-cluster
users:
- name: kubeadmin
  user:
    token: sha256~zzz
```

**Comment by praveenkumar** [comment]
> With non-suffixed/namespaced usernames

I don't think usernames are namespace suffix even https://github.com/crc-org/crc/issues/3940#issue-2028316040 I see username is prefix by apiserver so I am not sure where the namespace comes (in context field I agree it has namespace detail but not on the user side).

> this breaks easily, my 2 clusters will try to use the same token:

Is this `example-cluster` context created manually or done by some tool?

**Comment by cfergeau** [comment]
> Is this `example-cluster` context created manually or done by some tool?

I created it manually. Usernames created by other tools had the form `name: cfergeau/api-ci-xxx:6443` as in the first post, hence the suggestion to do the same for `crc`.

**Comment by anjannath** [comment]
> > while the microshift preset [...] the kubeconfig file is copied from the VM by crc
> 
> And the kubeconfig file created in the VM does not have suffixes?

yeah, that doesn't have suffixes

**Comment by cfergeau** [comment]
> I only want to update the user which we add not the whole kubeconfig file

Yes we only need to change `kubeadmin` and `developer` to `kubeadmin/api-crc-testing:6443` and `developer/api-crc-testing:6443` in the section specific to crc, we don't need to touch preexisting entries.

**Comment by praveenkumar** [comment]
> > > while the microshift preset [...] the kubeconfig file is copied from the VM by crc
> > 
> > 
> > And the kubeconfig file created in the VM does not have suffixes?
> 
> yeah, that doesn't have suffixes

kubeconfig created in the VM is created by openshift-installer and it only have `system-admin` right and we don't use this kubeconfig for user context. For user context we create `kubeadmin` and `developer` user and update it.

**Comment by anjannath** [comment]
> Yes I am referring to user section which is consumed by context not directly consumed by client. Also if we really want to have it in sync than I only want to update the user which we add not the whole kubeconfig file which is updated by different tools which is what #4020 is doing.
> 
>     * [main...praveenkumar:crc:issue_3920](https://github.com/crc-org/crc/compare/main...praveenkumar:crc:issue_3920)

if there are duplicate entries in the `users` section like below, it throws the error in https://github.com/crc-org/crc/issues/3940#issuecomment-1923594216

```
users:
- name: kubeadmin
  user:
    token: sha256~zzz
- name: kubeadmin
  user:
    token: sha256~zzz
```

i got that error by modifying the kubeconfig by hand, but if a `kubeadmin` user already existed and we wanted to add a new one, we'd overwrite the old one plus `kubeadmin`, `developer` are common names
